---
title: "Market"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)

```
**Last Updated: `r lubridate::today()`**

## Gainers

```{r fig-gainer}
readRDS("data/DF-GAINERS-LOSERS.RDS") %>%
  # gainer id == 1
  filter(id ==1) %>% 
  ggplot(aes(x = reorder(code, `% CHANGE`),
             y = `% CHANGE`,
             fill = sector )) +
  geom_col() +
  coord_flip() +
  labs(x = "", fill = "Sector")


```

## Losers

```{r fig-loser}
readRDS("data/DF-GAINERS-LOSERS.RDS") %>%
  # loser id == 2
  filter(id ==2) %>% 
  ggplot(aes(x = reorder(code, `% CHANGE`),
             y = `% CHANGE`,
             fill = sector )) +
  geom_col() +
  coord_flip() +
  labs(x = "", fill = "Sector")

```

## PE
```{r custom-funct-pe-plot}
# Custom function for PE plot
df_pe <- readRDS("data/DF-PE.RDS")
pe_plot <- function(sector_name){
  plot <- readRDS("data/DF-PE.RDS") %>%
    filter(sector == sector_name) %>% 
    arrange(pe) %>% 
    ggplot(aes(x = reorder(code, desc(pe)), y = pe, label = pe)) +
    geom_col() +
    coord_flip() +
    geom_text(size=2, color = "blue") +
    theme(axis.text.x = element_text(size = 7)) +
    labs(title = sector_name, x = "", y = "PE")
  return(plot)
}
```


```{r Bank}
pe_plot("Bank")
```
```{r pharma}
pe_plot("Pharmaceuticals & Chemicals")
```

```{r Engineering}
pe_plot("Engineering")
```
```{r Fuel & Power}
pe_plot("Fuel & Power")
```

```{r Financial Institutions}
pe_plot("Financial Institutions")
```

```{r Textile}
pe_plot("Textile")
```

```{r Cement}
pe_plot("Cement")
```

```{r IT}
pe_plot("IT")
```
```{r Miscellaneous}
pe_plot("Miscellaneous")
```
```{r Services-Real-Estate}
pe_plot("Services & Real Estate")
```

```{r Mutual-Funds}
pe_plot("Mutual Funds")
```

## Block Trade

```{r block}
readRDS("data/DF-BLOCK.RDS") %>% 
  ggplot(aes(x = reorder(code, `Value (in millions)`),
             y = `Value (in millions)`,
             fill = sector,
             label = round(`Value (in millions)`, 1))) +
  geom_col() +
  coord_flip() +
  labs(x = "",
       fill = "Sector",
       title = "Block Trade") +
  geom_text(size = 2) +
  theme(axis.text.y = element_text(size = 6))
```




